-- ============================================================
-- Gist App — Turso / libSQL Schema
-- SQLite-compatible — no Postgres extensions required
-- Apply with:  node scripts/setup-turso.js
-- ============================================================

-- 1. Users  (replaces Supabase auth.users + profiles)
CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY,                -- UUID generated by the API
  email      TEXT NOT NULL UNIQUE,
  password   TEXT NOT NULL,                   -- bcrypt hash — never expose to client
  role       TEXT NOT NULL DEFAULT 'user',    -- 'user' | 'admin'
  max_lists  INTEGER NOT NULL DEFAULT 4,
  max_items  INTEGER NOT NULL DEFAULT 50,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

-- 2. Lists
CREATE TABLE IF NOT EXISTS lists (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  color      TEXT NOT NULL DEFAULT '#7ac94b',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_lists_user ON lists(user_id);

-- 3. Items
CREATE TABLE IF NOT EXISTS items (
  id               TEXT PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  list_id          TEXT REFERENCES lists(id) ON DELETE CASCADE,
  name             TEXT NOT NULL,
  brand            TEXT,
  image_url        TEXT,
  nutriscore_grade TEXT,
  nova_group       INTEGER,
  gist_score       INTEGER,
  quantity         INTEGER NOT NULL DEFAULT 1,
  is_checked       INTEGER NOT NULL DEFAULT 0,  -- 0 = false, 1 = true
  item_type        TEXT NOT NULL DEFAULT 'recently_viewed',  -- 'recently_viewed' | 'list_item'
  created_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_items_user ON items(user_id);
CREATE INDEX IF NOT EXISTS idx_items_list ON items(list_id);
CREATE INDEX IF NOT EXISTS idx_items_type ON items(item_type);

-- 4. Products  (imported from Open Food Facts — same as Supabase version)
--    Populated by scripts/import-products.js — not user data.
--    additives stored as a JSON array string, e.g. '["E250","E621"]'
CREATE TABLE IF NOT EXISTS products (
  id               TEXT PRIMARY KEY,   -- OFF barcode / product code
  name             TEXT NOT NULL,
  brand            TEXT,
  nutriscore_grade TEXT,               -- a | b | c | d | e
  nova_group       INTEGER,
  gist_score       INTEGER,
  image_url        TEXT,
  additives        TEXT NOT NULL DEFAULT '[]',
  updated_at       TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_products_name  ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_score ON products(gist_score DESC);

-- Full-text search for products (SQLite FTS5)
-- This virtual table is populated by scripts/setup-turso.js after the import.
-- Re-populate any time you re-run the import script.
CREATE VIRTUAL TABLE IF NOT EXISTS products_fts USING fts5(
  id    UNINDEXED,
  name,
  brand,
  content='products',
  content_rowid='rowid'
);

-- ============================================================
-- Promote a user to admin — run in the Turso shell or setup script:
--   UPDATE users SET role = 'admin' WHERE email = 'your@email.com';
-- ============================================================
